[package]
name = "netcdf2ascii-rust"
version = "0.1.0"
authors = ["Michael Giansiracusa <giansiracumt@ornl.gov>"]
edition = "2018"

[dependencies]
netcdf = {version = "~0.3.1"}
log = {version = "~0.4.6"}
structopt = "0.3.7"